version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - run:
          name: install System dependency and active python venv
          command: |
            sudo apt-get install software-properties-common
            sudo add-apt-repository ppa:mc3man/trusty-media -y
            sudo add-apt-repository ppa:ethereum/ethereum -y
            sudo apt-get update
            sudo apt-get install -y solc
            sudo apt-get install -y python3-venv
            sudo apt-get install -y python3-dev
            sudo apt-get install -y libssl-dev
            sudo apt-get install -y g++
            sudo apt-get install -y git
            sudo apt-get install ffmpeg -qqy
            sudo apt-get install -y ethereum=1.7.3*
            python3 -m venv venv
            . venv/bin/activate

      - checkout


      - run:
          name: Python dependency installation
          command: |
            . venv/bin/activate
            python -m pip install --upgrade setuptools
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
            python --version
            pip --version
            python -m pip --version